name: flutter_clean_architecture_template
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.9.0

dependencies:
  connectivity_plus: ^7.0.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^3.0.0
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.1
  get_it: ^8.2.0
  go_router: ^16.2.2
  hive_ce: ^2.12.0
  hive_ce_flutter: ^2.3.2
  image_cropper: ^8.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  logger: ^2.5.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  dio: ^5.9.0
  go_transitions: ^0.8.2
  shimmer: ^3.0.0
  fluttertoast: ^9.0.0
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.9.2
  rename_app: ^1.6.5 #dart run rename_app:main all="App Name"
  change_app_package_name: ^1.5.0 #dart run change_app_package_name:main com.new.package.name

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icons/splash-icon-384x384.png"
  android: true
  ios: true
  web: true
  # command: dart run flutter_native_splash:create

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/icons/
    - assets/pngs/
    - assets/svgs/
    - .env

  fonts:
    - family: NeueHaasDisplay
      fonts:
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayBlack.ttf
          weight: 900
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayBlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayBoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayLight.ttf
          weight: 300
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayLightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayMedium.ttf
          weight: 500
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayMediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayRoman.ttf
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayRomanItalic.ttf
          style: italic
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayThin.ttf
          weight: 100
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayThinItalic.ttf
          weight: 100
          style: italic
    - family: IntegralCF
      fonts:
        - asset: assets/fonts/integral/IntegralCF-Bold.otf
          weight: 700
        - asset: assets/fonts/integral/IntegralCF-BoldOblique.otf
          weight: 700
          style: italic
        - asset: assets/fonts/integral/IntegralCF-DemiBold.otf
          weight: 600
        - asset: assets/fonts/integral/IntegralCF-DemiBoldOblique.otf
          weight: 600
          style: italic
        - asset: assets/fonts/integral/IntegralCF-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/integral/IntegralCF-ExtraBoldOblique.otf
          weight: 800
          style: italic
        - asset: assets/fonts/integral/IntegralCF-Heavy.otf
          weight: 900
        - asset: assets/fonts/integral/IntegralCF-HeavyOblique.otf
          weight: 900
          style: italic
        - asset: assets/fonts/integral/IntegralCF-Medium.otf
          weight: 500
        - asset: assets/fonts/integral/IntegralCF-MediumOblique.otf
          weight: 500
          style: italic
        - asset: assets/fonts/integral/IntegralCF-Regular.otf
          weight: 400
        - asset: assets/fonts/integral/IntegralCF-RegularOblique.otf
          weight: 400
          style: italic
